language: android
env:
  global:
  - MALLOC_ARENA_MAX=2
  - secure: gDjA3rO/+HdOMuEyjLHN4I6XFe3sNTsFDnwvBT70oOQvTMMnKgVS1IhKy/6aPfT2bf9miS/TxB2tyE9WjHkP3Uhca4COViL+7QldBXXrEEStzBViSj3t2EUHaE+qd6IlH6E9DbOzloJNmnwVxRuOL602t2KCKazU6iZsN5N7pmY=
  matrix:
  - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    ENABLE_GPL_THIRD_PARTIES=0 BUILD_VIDEO=1 BUILD_OPENH264=1 ENABLE_OPENH264_DECODER=1
    BUILD_X264=0 BUILD_AMRNB=full BUILD_AMRWB=1 BUILD_ZRTP=1 BUILD_SILK=1 BUILD_G729=1
    BUILD_TUNNEL=0 BUILD_WEBRTC_AECM=1 USE_JAVAH=1 BUILD_FOR_X86=1 BUILD_SQLITE=1
    BUILD_TLS=1 BUILD_WEBRTC_ISAC=1 BUILD_OPUS=1 BUILD_UPNP=1 BUILD_MATROSKA=0 BUILD_ILBC=1
#sudo: false
#addons:
#  apt:
#    packages:
#    - ia32-libs
#    - ia32-libs-multiarch
#    - yasm
#    - nasm
#    - curl
#    - ant
#    - rsync
#    - autoconf
#    - automake
#    - libtool
#    - pkg-config
#    - bc
#    - libwww-perl
#    - p7zip
cache:
  apt: true
  bundler: true
  ccache: true
  directories:
  - $HOME/.ccache
  - $HOME/ndk.bin
  - $HOME/android-ndk-r10d
  - $HOME/android-sdk-linux
  - $HOME/liblinphone-android-sdk-2.4.1-29-g7fbb2e8.zip
  - $HOME/libs
  - $HOME/submodules
before_install:
- sudo apt-get update 
- sudo apt-get install -qq --force-yes yasm nasm curl ant rsync autoconf automake
  libtool pkg-config bc libwww-perl
- sudo apt-get install -qq --force-yes p7zip
- if [ ! -e ndk.bin ]; then
    if [ `uname -m` = x86_64 ]; then
      wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin -O ndk.bin ;
    else
      wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin -O ndk.bin ;
    fi ;
  fi
- if [ ! -d android-ndk-r10d ] ; then 7zr x ndk.bin 2>&1 | grep -v Extracting ; fi
- export ANDROID_NDK=$HOME/android-ndk-r10d
- export ANDROID_HOME=$HOME/android-sdk-linux
- export PATH=${ANDROID_NDK}:${ANDROID_NDK}/ndk-build:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PATH
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes ia32-libs ia32-libs-multiarch ; fi || true
- sudo dpkg --add-architecture i386 || true
- sudo apt-get install -y --force-yes libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386 || true
android:
  components:
  - build-tools-19.1.0
  - android-19
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
#  - sys-img-armeabi-v7a-android-19
#  - sys-img-x86-android-17
before_script:
- echo "Extracting pre-build binary sdk"
- if [ ! -f liblinphone-android-sdk-2.4.1-29-g7fbb2e8.zip ]; then
    wget https://vtcsecurellc.github.io/belledonne_binaries/2015-08-01/liblinphone-android-sdk-2.4.1-29-g7fbb2e8.zip ;
  fi
- if [ ! -f libs/armeabi-v7a/liblinphone-armeabi-v7a.so ]; then
    unzip liblinphone-android-sdk-2.4.1-29-g7fbb2e8.zip ;
  fi
- git config --global gc.auto 0
- git config --global pack.windowMemory 60m
- git config --global pack.packSizeLimit 60m
- git config --global pack.deltacachesize 60m
- git config --global core.packedgitwindowsize 50m
- git config --global core.packedgitlimit 50m
- git config --global core.deltacachesize 50m
- echo "Starting to update submodules"
- if [ ! -e "submodules/linphone/.git" ]; then
    git clone git://github.com/VTCSecureLLC/linphone.git "submodules/linphone" ;
  fi
- if [ ! -e "submodules/linphone/mediastreamer2/.git" ]; then
    git clone git://git.linphone.org/mediastreamer2.git "submodules/linphone/mediastreamer2" ;
  fi
- if [ ! -e "submodules/linphone/oRTP/.git" ]; then
    git clone git://git.linphone.org/ortp.git "submodules/linphone/oRTP" ;
  fi
- if [ ! -e "submodules/externals/gsm/.git" ]; then
    git clone git://git.linphone.org/gsm.git "submodules/externals/gsm" ;
  fi
- if [ ! -e "submodules/externals/speex/.git" ]; then
    git clone git://git.linphone.org/speex "submodules/externals/speex" ;
  fi
- if [ ! -e "submodules/msilbc/.git"]; then
    git clone git://git.linphone.org/msilbc.git "submodules/msilbc" ;
  fi
- if [ ! -e "submodules/libilbc-rfc3951/.git"]; then
    git clone git://git.linphone.org/libilbc-rfc3951.git "submodules/libilbc-rfc3951" ;
  fi
- if [ ! -e "submodules/externals/ffmpeg/.git"]; then
    git clone git://git.linphone.org/ffmpeg.git "submodules/externals/ffmpeg" ;
  fi
- if [ ! -e "submodules/externals/x264/.git"]; then
    git clone git://git.linphone.org/x264.git "submodules/externals/x264" ;
  fi
- if [ ! -e "submodules/msx264/.git"]; then
    git clone git://git.linphone.org/msx264.git "submodules/msx264" ;
  fi
- if [ ! -e "submodules/externals/opencore-amr/.git"]; then
    git clone git://git.linphone.org/opencore-amr.git "submodules/externals/opencore-amr" ;
  fi
- if [ ! -e "submodules/msamr/.git"]; then
    git clone git://git.linphone.org/msamr "submodules/msamr" ;
  fi
- if [ ! -e "submodules/externals/libvpx/.git"]; then
    git clone https://chromium.googlesource.com/webm/libvpx "submodules/externals/libvpx" ;
  fi
- if [ ! -e "submodules/bzrtp/.git"]; then
    git clone git://git.linphone.org/bzrtp.git "submodules/bzrtp" ;
  fi
- if [ ! -e "submodules/externals/srtp/.git"]; then
    git clone git://git.linphone.org/srtp.git "submodules/externals/srtp" ;
  fi
- if [ ! -e "submodules/mssilk/.git"]; then
    git clone git://git.linphone.org/mssilk.git "submodules/mssilk" ;
  fi
- if [ ! -e "submodules/externals/vo-amrwbenc/.git"]; then
    git clone git://git.linphone.org/vo-amrwbenc.git "submodules/externals/vo-amrwbenc" ;
  fi
- if [ ! -e "submodules/bcg729/.git"]; then
    git clone git://git.linphone.org/bcg729.git "submodules/bcg729" ;
  fi
- if [ ! -e "submodules/belle-sip/.git"]; then
    git clone git://git.linphone.org/belle-sip "submodules/belle-sip" ;
  fi
- if [ ! -e "submodules/externals/antlr3/.git"]; then
    git clone git://git.linphone.org/antlr3.git "submodules/externals/antlr3" ;
  fi
- if [ ! -e "submodules/externals/libxml2/.git"]; then
    git clone git://git.gnome.org/libxml2 "submodules/externals/libxml2" ;
  fi
- if [ ! -e "submodules/externals/libupnp/.git"]; then
    git clone git://git.linphone.org/libupnp.git "submodules/externals/libupnp" ;
  fi
- if [ ! -e "submodules/externals/cunit/.git"]; then
    git clone git://git.linphone.org/cunit.git "submodules/externals/cunit" ;
  fi
- if [ ! -e "submodules/externals/axmlrpc/.git"]; then
    git clone git://git.linphone.org/axmlrpc.git "submodules/externals/axmlrpc" ;
  fi
- if [ ! -e "submodules/externals/polarssl/.git"]; then
    git clone git://git.linphone.org/polarssl.git "submodules/externals/polarssl" ;
  fi
- if [ ! -e "submodules/externals/opus/.git"]; then
    git clone https://github.com/VTCSecureLLC/opus.git "submodules/externals/opus" ;
  fi
- if [ ! -e "submodules/mswebrtc/.git"]; then
    git clone git://git.linphone.org/mswebrtc.git "submodules/mswebrtc" ;
  fi
- if [ ! -e "submodules/msopenh264/.git"]; then
    git clone git://git.linphone.org/msopenh264.git "submodules/msopenh264" ;
  fi
- if [ ! -e "submodules/externals/openh264/.git"]; then
    git clone https://github.com/cisco/openh264 "submodules/externals/openh264" ;
  fi
- if [ ! -e "submodules/externals/libmatroska/.git"]; then
    git clone https://github.com/Matroska-Org/foundation-source.git "submodules/externals/libmatroska" ;
  fi
- if [ ! -e "submodules/externals/webrtc/.git"]; then
    git clone git://git.linphone.org/webrtc.git "submodules/externals/webrtc" ;
  fi
- git submodule update --init --recursive
- echo "Finished updating submodules"
script:
- bash -xc '
  echo "Running make" ;
  find . -name 'ndk-build' -print ;
  ls -lsR $HOME/android-ndk-r10d/
  touch /tmp/make.out ;
  ( COUNTER=0; 
  while [  $COUNTER -lt 30 ]; do 
    echo The counter is $COUNTER ;
    let COUNTER=COUNTER+1 ;
    sleep 60;
    echo "Muted, but still building. Last 100 lines:";
    tail -100 /tmp/make.out;
  done;
  echo Timing out after 30 minutes. ) &
  MUTED_PID=$! ;
  make > /tmp/make.out 2>&1 ;
  MAKE_RESULT=$@ ;
  tail -1000 /tmp/make.out ;
  kill $MUTED_PID ;
  exit $MAKE_RESULT'
#- make liblinphone-android-sdk
#- make mediastreamer2-sdk
after_script:
- ./Tools/github_release.sh
notifications:
  slack:
    secure: PbV38W/sM4KC9zan3fNkMhqOl9uISNkqtmqrKruuNXMM0uOXEmAP57cyHP3k8B2UEAECXVRRmD3VtVJmQt+y9abaR1YUIRdMlRgkSoXmy4vAVh9tveZvNkohFzlfNCLS4oGiT/bodCuLpVP7AwT97l0eRZXABCx1+x0Ju7sHyXA=
  flowdock:
    secure: RGcyuffpq84c1ku6htGkmDnnwvcI/xQreEDowCGVzYPa2ih5birV3GayMMaZoxG+Xpc9Qjkq5wm5wwsqzMQMryg2SesqHZ22tdDLT8oKEmNdZRoUKr6PjJPbcy+YCrNXcqP3fWUNd0FfApiDOMM7q+CI7yl49auJigE0wOKG4Z4=
