language: android
env:
  global:
  - MALLOC_ARENA_MAX=2
  - secure: v49TqTGv7lGyIxBcltIdOaDMrBF6aqaRRSRB+2zrMyJtZVrHg9sSYBdBmsoyWYXYCQaxFO1ggddXkz7oklaXFT0OxIAv8Xyivd14FtmJR/ho5POIl9Cpxhnq0qcg8tnSoRgxg2Z+iMiRXeMgoyW0wqxNisye17ncoMU9RXR+v2SZVm1oQ6/IRVv2MK9cYLPQ0nauKMBfH6Hvl39s0YuObvlbxm5cKou+CK5JfzisB2wPRf6RcPMmdNxVI1jvIrfQ1IjDNUt3f5izmHMOyekvdOk/LIWKEaaw2ZBhXkUTRrRUjLEIo0B4nUnIF8w8txg8kXviLbXQ2413qLt9askQEUT6xYfUHc/PxMLjycpqr7bbCMnqtILLCy2nAiy8ZeidNd1QgNNNeNtw8msH4B2elRPrDld+cXTrj+66z1T9xiaTh9CUwVpdJrjrkcMzIIdu/x1qAZW5bIevSvK35bxaPmq6Y5HZDDySm2j9KJgaabwGSA1xB75HYU9WMD8mWToI+6ERvvpKB4sfFS/4vGSnD8WaQVJMbxRxfpLeVuC00dFSjz5sS073I9hkdc7LUEcGt13dfxFB841Ddag3QUZ/MweRlkz5zVcePFYzxzhl7yFPlPk8DBMIunMjXKIrDefWznhfO+OG6/W/7j+keukmWJYYndlAfqCKO9TdVVYe39M=
  - secure: lrnzhMmgnUzBW9jmcKdSBtdKc1llI1LcUXLeOeAfimzNMJUCQzGtY7unSbxZ28bc9l/qAjYkoDcHqjhhLk55jg4gcxHfkGj6WhxIg0xpTixh/iSjNvg8X59yntUsQt1f4/Xh/f3K9YSnmVbLN+DaBlAuilMr0CQZDfne90HVqK1Vu1RuojGKYMHGCH80Ic1FCvYRb7JMq6vB8l0OI0o9UldQajWJN0icM1826G1V/gFVW4MUhcOEGqpxVchCF9n8ucR5vxgtvv+bRpPxrfVINPQEMTiu7OpadoSCEWuBTg1ZJYF2Et/CRdq2vhp+GtDk3/RdFrKuqv7SqxwCsq258kE7lbAOPi5w81b0LiXq4XknCy2G2qyoU2KMI5tGmtPB4aIyH1mXAu1uykzqJc511ZlLfB2OK2DpJEoxlNJ1VnBFlJLmCSVQjVV9xgaZ35V/0KWo0QCOzTTmg38u5y/jC+2q4PL/qFz+1N8nXMXYxXKgZRWT2lY1rJXBvLo5//nzw06vnqGA1DRMQ+Y1ymHXY5beqj450/R2bKOVtb8312uJ3katdLbp8g9lkuMPCfMR+y8MLjLa2wXx5gp2yebqAzf81fVAhYiIlOpSRpz+uQGEz1y1Pd6okLiEIE7uqO8UuBeIwQlD+ThuylIlTV2G8tBnuq5CDu7Ejhy/hUiWbVU=
  - secure: ZRAQk9vlnXcuD4/964/Vwvx9RinXoIrBzMeZ9vj5dxGIrvTB0gCkHzVxTx/A/O2tHjUC0fhJPfbMUqDE/O9nJZMMknCGuJ6+c84aSqTfcXm8rqZ4Z1jIPbDAxuPNHl5WzO7N6O96CiXvkkLdgZGn85SbrhatOKpoyhHUkosEkxyrDpz2bbM2pYw07ynUWDvm0/lN9gg9iVqmHwLSYghCka3G01CLqXT7fcEqUUnuHnu+jHHHD3MWFH6+nZaZrU5hfh065T5bom45a4ZIK0gsEpar06kc35vRrDfGqIW3TW2hLpT4hC/lpiq/pcWZEdZYOxYKWd/aNKmiMKVu2hUE+BLI1n+AP8Ma1ddgTKXQpnBtWfMJ+0EfY1X9TbKuvC/DZBtmluZ7Px3n5irDl6ABnh9hgjpe0X1d26dXygBIvP4ZrDhIEZrAAuaFMJBJ/zRLjd48nwCDIMj/GG3jpEkNJd5E1erSRACzo5JTT+QSsOIeFdx+nETcmpXUPhbx00jN6R3l2v4AqWJl5vC4tOL545Qt/LxbZIxuq/g9inj8u2BAJ9gagmSwWfwucqHMNc55f2PjlwwXlRZ+6m7Xr+nwr1Kpw4rDLnKuSmLmRY/sIMLsgjaWMGNA9s+hTd+9/rfYbLR9fyY8klyAjDlHG4RwuXFcXEA056r/6oRavABZJv0=
  matrix:
  - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    ENABLE_GPL_THIRD_PARTIES=0 BUILD_VIDEO=1 BUILD_OPENH264=1 ENABLE_OPENH264_DECODER=1
    BUILD_X264=0 BUILD_AMRNB=full BUILD_AMRWB=1 BUILD_ZRTP=1 BUILD_SILK=1 BUILD_G729=1
    BUILD_TUNNEL=0 BUILD_WEBRTC_AECM=1 USE_JAVAH=1 BUILD_FOR_X86=1 BUILD_SQLITE=1
    BUILD_TLS=1 BUILD_WEBRTC_ISAC=1 BUILD_OPUS=1 BUILD_UPNP=1 BUILD_MATROSKA=0 BUILD_ILBC=1
sudo: false
addons:
  apt:
    packages:
    - yasm
    - nasm
    - curl
    - ant
    - rsync
    - autoconf
    - automake
    - libtool
    - pkg-config
    - bc
    - libwww-perl
    - ruby
cache:
  apt: true
  bundler: true
  ccache: true
  directories:
  - "$HOME/.ccache"
before_install:
- if [ `uname -m` = x86_64 ]; then
    wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin -O ndk.bin ;
  else 
    wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86.bin -O ndk.bin ;
  fi
- chmod 755 ndk.bin ; ./ndk.bin 2>&1 | grep -v Extracting
- export ANDROID_NDK=$PWD/android-ndk-r10e
- export PATH=${ANDROID_NDK}:${ANDROID_NDK}/ndk-build:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PATH
- export NDK_CACHE=ccache
- export ANDROID_MOST_RECENT_TARGET=android-19
- which bundler || gem install bundler
- bundle install
android:
  components:
  - build-tools-19.1.0
  - build-tools-20.0.0
  - build-tools-22.0.1
  - android-19
  - android-20
  - android-22
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - addon-google_apis-google-20
  - addon-google_apis-google-22
before_script:
- echo "Starting to update submodules"
- if [ ! -d submodules/linphone/oRTP/.git ]; then rm -fr submodules/linphone/oRTP/
  ; git clone git://git.linphone.org/ortp.git submodules/linphone/oRTP ; fi
- if [ ! -d submodules/linphone/mediastreamer2/.git ]; then rm -fr submodules/linphone/mediastreamer2/
  ; git clone git://git.linphone.org/mediastreamer2.git submodules/linphone/mediastreamer2
  ; fi
- if [ ! -d submodules/mswebrtc/webrtc/.git ]; then rm -fr submodules/mswebrtc/webrtc/
  ; git clone git://git.linphone.org/webrtc.git submodules/mswebrtc/webrtc ; fi
- git submodule update --init --recursive
- echo "Finished updating submodules"
script:
- android list target -c || true
- "./Tools/prepare_crashlytics.sh"
#- gradle prepareDebugDependencies ; find . -name '*crashlytics*' -print
- "./Tools/travis_script.sh"
before_cache:
- echo "before_cache"
after_success:
- echo "after_success"
- "./Tools/github_release.sh"
after_failure:
- echo "after_failure"
after_script:
- find . -name '*.apk' -print
notifications:
  slack:
    secure: PbV38W/sM4KC9zan3fNkMhqOl9uISNkqtmqrKruuNXMM0uOXEmAP57cyHP3k8B2UEAECXVRRmD3VtVJmQt+y9abaR1YUIRdMlRgkSoXmy4vAVh9tveZvNkohFzlfNCLS4oGiT/bodCuLpVP7AwT97l0eRZXABCx1+x0Ju7sHyXA=
  flowdock:
    secure: RGcyuffpq84c1ku6htGkmDnnwvcI/xQreEDowCGVzYPa2ih5birV3GayMMaZoxG+Xpc9Qjkq5wm5wwsqzMQMryg2SesqHZ22tdDLT8oKEmNdZRoUKr6PjJPbcy+YCrNXcqP3fWUNd0FfApiDOMM7q+CI7yl49auJigE0wOKG4Z4=
