language: android
env:
  global:
  - MALLOC_ARENA_MAX=2
  - secure: DTPtpznj7wMOBbwPemqbBnAr/IYo2EHoXCukW5SFdqq/lngHKGogRGDUoxpQi7CpaJSoR+Y8EIuXaTNHjN6AxhGaW8nIyvhZR3zc0hUKYi7JsT6wxIHybqA3AQv8jJjh6w0ut9Nd8FO7b5ko7VoduzhkTpNZ9H1trH1Fu3SvMwmpu1fRobh/BRxUPeg0XfmVbR3WK5wHXjIw+uEKnPOAirFsGB8RCQZ8fSHbgWy8IW3aVVdBSJCxHpTRqPGe8iv/aJ+rcb+cg5F/ZfUQiCKG4hqPQ3ICJisKWRWui08UsI3U6/wcYVNh3ReiKUwXGqd9nI+wdb+fjpwY8IS7n/7IyfFql3cZle3PeI7VyjJ2wO6BnncNT2eZwy2L4Qoamu16k5vlKj7J5XFlLjuFr9TqPsGsYgdyko9bglJooIRzFOeUw8Il9mu19861QeDm0nZ915Z+x1lqMiGsAdGwpylrgKyGCJ0Wfu3A8C2tjrJl5F13g6jy/kAxYcbAJ5DbxGx15moAi6hks8XsVVrgpDXWHKMynf/Q6iWSHRL9ad4M23BjNQhg2kdJVBF6KcFuBoyLaQv5T7NowTRlk/n5XuI+88dpCdfXIV6ufJ6MiWazdhwiXDKJYqaKHmDNxHArCK5bkxlDrlVTV29M6ajfFY9zQdey+dtpHMT3xn1TkcGzJjQ=
  - secure: NnbWYh1cxU1hKFTMfHA2vH24b+mMolPgQICK8QVoJ4xFBnszBwthE4oYAU7cvBzBzz7mLeAIq+abt/uVc6pKVKxC5rf2OY6toHtzjCrNz47A/K8H8vw5UUYC4G8wFtcFB6u0ioQA5drC0nvIlllWbhSWmJHnu8qcoqj0K14iw4dIXmQWRjxYcMf8ejm3CHQtjnrFdsvLySuIn6zYghstm8EA+3rqKTeBcPpiFpmwIFnicht/lTShP7qjenb91yd5u4A7ODvSkqrLuXOFTTji8KsPovEMiP4dLekcaqAcc8ifaST09SVKljuCHv3ZKUSbk9zUsc4ARYn5x3e0QSlWTFipXUFQR0/b4VWj4Qu4osOTxIZ+io/u816t656BZQE98WSNi34QwmLp3Q3G9PnEtu9cx6QIJaapWSiJmOp+GEQrhg9+V5YGikaE/1OHqpQdlOJ0mxVJ56K+SJ5hY/9/fJx+OS4I5SAtncCHTIN3lAMDeyxsjcZxDmNbTb+ei3A55banYSy28jqoV7W9NgH/AelKLhVP6P8MR+wavbQ+FKMKbvd3Fc7Av5B1k6kNtKb3JwUgh70RoPIj22qps7eNM1QfoVys60ZK89psIZ6NqcCvQ67FvUU2uXWguNnscSf3VdPfPoACdYGvl8LaBeLA1pl3MA0eChBIc31bJMe7Vfo=
  - secure: RML1/WXM1hcbYTQ4e6NsfibXBpSHL9J80UNyL0wpj8bCidD+Ewb9ImaVQ8BG/rZaYlMzwUAD/jGy7YTQBpYjgwg5P2k/XUOQGiuK53qzcm+R1naxhoxLC3U4NKP2kTo4kGinoMMdmozC5xq68/SPLXYMWRSoUFQM0zk+Y+pjjykOkN4PVMk6ovt4VhMBqxehwfCmwdB5yFz3JwefI274SN5nAG8o9XQQpUSyKcDE0qrVgXp9JllRbfdiAFM+K5msKhVhVBioJUsmDRpq4ESY/Bocz/BGCnmrMaqPm6YwHmkNVcNNAd+FzL35SZ4X7vI48ssHSs3RB910cYWaR8ryjdjQHm1dq+TVRiKllzbNNChU1QiALUnNoHruZeCNL/TL3L67g1n7b6ay0wTr1CH49GxFcqP+CvipcIKFODJ0hllQy5gcr5r09YQO1w5igfVmU83SeVcVaOoaSazvyzo3xUNzvQ7C1eB91PjAdKho4U64LcPzzuzEh14PDsEsyxTZulrL3tvjIr4kSUKfs0Z1vGwPxMiZw3qSaIYBP+CqRJ7MozLO8u2lIQlVpAErHpUlq/jGOo/E3XfAHyoN9IhtvTM2gguEedLw3vPh/hKx+A3AI8LrFa6WHeumhCGannswxi71hUz/uUyP7k900kyAWWGXLFEU3IO3RO93LE4I/Tk=
  matrix:
  - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    ENABLE_GPL_THIRD_PARTIES=0 BUILD_VIDEO=1 BUILD_OPENH264=1 ENABLE_OPENH264_DECODER=1
    BUILD_X264=0 BUILD_AMRNB=full BUILD_AMRWB=1 BUILD_ZRTP=1 BUILD_SILK=1 BUILD_G729=1
    BUILD_TUNNEL=0 BUILD_WEBRTC_AECM=1 USE_JAVAH=1 BUILD_FOR_X86=1 BUILD_SQLITE=1
    BUILD_TLS=1 BUILD_WEBRTC_ISAC=1 BUILD_OPUS=1 BUILD_UPNP=1 BUILD_MATROSKA=0 BUILD_ILBC=1
cache:
  apt: true
  bundler: true
  ccache: true
  directories:
  - "$HOME/.ccache"
  - ndk.bin
  - android-ndk-r10d
  - android-sdk-linux
  - liblinphone-android-sdk-2.4.1-29-g7fbb2e8.zip
  - libs
  - submodules
before_install:
- sudo add-apt-repository ppa:git-core/ppa -y
- sudo apt-get update
- sudo apt-get install -qq --force-yes yasm nasm curl ant rsync autoconf automake
  libtool pkg-config bc libwww-perl ruby-bundler p7zip git-core
- if [ ! -e ndk.bin ]; then if [ `uname -m` = x86_64 ]; then wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin
  -O ndk.bin ; else wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin
  -O ndk.bin ; fi ; fi
- if [ ! -d android-ndk-r10d ] ; then 7zr x ndk.bin 2>&1 | grep -v Extracting ; fi
- export ANDROID_NDK=$(pwd)/android-ndk-r10d
- export ANDROID_HOME=$(pwd)/android-sdk-linux
- export PATH=${ANDROID_NDK}:${ANDROID_NDK}/ndk-build:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PATH
- export NDK_CACHE=ccache
- export ANDROID_MOST_RECENT_TARGET=android-19
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes ia32-libs
  ia32-libs-multiarch ; fi || true
- sudo dpkg --add-architecture i386 || true
- sudo apt-get install -y --force-yes libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386
  || true
- bundle install
android:
  components:
  - build-tools-19.1.0
  - android-19
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
before_script:
- git config --global gc.auto 0
- git config --global pack.windowMemory 60m
- git config --global pack.packSizeLimit 60m
- git config --global pack.deltacachesize 60m
- git config --global core.compression 0
- git config --global core.packedgitwindowsize 50m
- git config --global core.packedgitlimit 50m
- git config --global core.deltacachesize 50m
- echo "Starting to update submodules"
- if [ ! -e "submodules/linphone/.git" ]; then git clone git://github.com/VTCSecureLLC/linphone.git
  "submodules/linphone" ; fi
- sudo service postgresql stop || true
- sudo pkill postgres || true
- sudo ps axuw ; free ; df -k ; ls -la /var/ramfs/ || true
- if [ ! -e "submodules/linphone/mediastreamer2/.git" ]; then
    set -x ;
    git clone --depth 1 git://github.com/VTCSecureLLC/mediastreamer2.git "submodules/linphone/mediastreamer2" &&
    ( set -x; cd submodules/linphone/mediastreamer2 && git fetch --unshallow && git pull --all ) ;
  fi
- if [ ! -e "submodules/linphone/oRTP/.git" ]; then git clone git://github.com/VTCSecureLLC/ortp.git
  "submodules/linphone/oRTP" ; fi
- if [ ! -e "submodules/externals/gsm/.git" ]; then git clone git://git.linphone.org/gsm.git
  "submodules/externals/gsm" ; fi
- if [ ! -e "submodules/externals/speex/.git" ]; then git clone git://git.linphone.org/speex
  "submodules/externals/speex" ; fi
- if [ ! -e "submodules/msilbc/.git"]; then git clone git://git.linphone.org/msilbc.git
  "submodules/msilbc" ; fi
- if [ ! -e "submodules/libilbc-rfc3951/.git"]; then git clone git://git.linphone.org/libilbc-rfc3951.git
  "submodules/libilbc-rfc3951" ; fi
- if [ ! -e "submodules/externals/ffmpeg/.git"]; then git clone git://git.linphone.org/ffmpeg.git
  "submodules/externals/ffmpeg" ; fi
- if [ ! -e "submodules/externals/x264/.git"]; then git clone git://git.linphone.org/x264.git
  "submodules/externals/x264" ; fi
- if [ ! -e "submodules/msx264/.git"]; then git clone git://git.linphone.org/msx264.git
  "submodules/msx264" ; fi
- if [ ! -e "submodules/externals/opencore-amr/.git"]; then git clone git://git.linphone.org/opencore-amr.git
  "submodules/externals/opencore-amr" ; fi
- if [ ! -e "submodules/msamr/.git"]; then git clone git://git.linphone.org/msamr
  "submodules/msamr" ; fi
- if [ ! -e "submodules/externals/libvpx/.git"]; then git clone https://chromium.googlesource.com/webm/libvpx
  "submodules/externals/libvpx" ; fi
- if [ ! -e "submodules/bzrtp/.git"]; then git clone git://git.linphone.org/bzrtp.git
  "submodules/bzrtp" ; fi
- if [ ! -e "submodules/externals/srtp/.git"]; then git clone git://git.linphone.org/srtp.git
  "submodules/externals/srtp" ; fi
- if [ ! -e "submodules/mssilk/.git"]; then git clone git://git.linphone.org/mssilk.git
  "submodules/mssilk" ; fi
- if [ ! -e "submodules/externals/vo-amrwbenc/.git"]; then git clone git://git.linphone.org/vo-amrwbenc.git
  "submodules/externals/vo-amrwbenc" ; fi
- if [ ! -e "submodules/bcg729/.git"]; then git clone git://git.linphone.org/bcg729.git
  "submodules/bcg729" ; fi
- if [ ! -e "submodules/belle-sip/.git"]; then git clone git://git.linphone.org/belle-sip
  "submodules/belle-sip" ; fi
- if [ ! -e "submodules/externals/antlr3/.git"]; then git clone git://git.linphone.org/antlr3.git
  "submodules/externals/antlr3" ; fi
- if [ ! -e "submodules/externals/libxml2/.git"]; then git clone git://git.gnome.org/libxml2
  "submodules/externals/libxml2" ; fi
- if [ ! -e "submodules/externals/libupnp/.git"]; then git clone git://git.linphone.org/libupnp.git
  "submodules/externals/libupnp" ; fi
- if [ ! -e "submodules/externals/cunit/.git"]; then git clone git://git.linphone.org/cunit.git
  "submodules/externals/cunit" ; fi
- if [ ! -e "submodules/externals/axmlrpc/.git"]; then git clone git://git.linphone.org/axmlrpc.git
  "submodules/externals/axmlrpc" ; fi
- if [ ! -e "submodules/externals/polarssl/.git"]; then git clone git://git.linphone.org/polarssl.git
  "submodules/externals/polarssl" ; fi
- if [ ! -e "submodules/externals/opus/.git"]; then git clone https://github.com/VTCSecureLLC/opus.git
  "submodules/externals/opus" ; fi
- if [ ! -e "submodules/mswebrtc/.git"]; then git clone git://git.linphone.org/mswebrtc.git
  "submodules/mswebrtc" ; fi
- if [ ! -e "submodules/msopenh264/.git"]; then git clone git://git.linphone.org/msopenh264.git
  "submodules/msopenh264" ; fi
- if [ ! -e "submodules/externals/openh264/.git"]; then git clone https://github.com/cisco/openh264
  "submodules/externals/openh264" ; fi
- if [ ! -e "submodules/externals/libmatroska/.git"]; then git clone https://github.com/Matroska-Org/foundation-source.git
  "submodules/externals/libmatroska" ; fi
- if [ ! -e "submodules/externals/webrtc/.git"]; then git clone git://git.linphone.org/webrtc.git
  "submodules/externals/webrtc" ; fi
- git submodule update --init --recursive
- echo "Finished updating submodules"
script:
- sudo ps axuw ; free ; df -k ; ls -la /var/ramfs/ || true
- android list target -c || true
- bash -xc ' echo "Running make" ; touch /tmp/make.out ; ( COUNTER=0; while [  $COUNTER
  -lt 30 ]; do echo The counter is $COUNTER ; let COUNTER=COUNTER+1 ; sleep 60; echo
  "Muted, but still building. Last 100 lines:"; tail -100 /tmp/make.out; done; echo
  Timing out after 30 minutes. ) & MUTED_PID=$! ; make > /tmp/make.out 2>&1 ; MAKE_RESULT=$@
  ; tail -1000 /tmp/make.out ; kill $MUTED_PID ; exit $MAKE_RESULT'
before_cache:
- echo "before_cache"
after_success:
- echo "after_success"
after_failure:
- echo "after_failure"
after_script:
- find . -name '*.apk' -print
#- if [ "$TRAVIS_BRANCH" = "master" ]; then
- ./Tools/prepare_crashlytics.sh
- ./Tools/github_release.sh
notifications:
  slack:
    secure: PbV38W/sM4KC9zan3fNkMhqOl9uISNkqtmqrKruuNXMM0uOXEmAP57cyHP3k8B2UEAECXVRRmD3VtVJmQt+y9abaR1YUIRdMlRgkSoXmy4vAVh9tveZvNkohFzlfNCLS4oGiT/bodCuLpVP7AwT97l0eRZXABCx1+x0Ju7sHyXA=
  flowdock:
    secure: RGcyuffpq84c1ku6htGkmDnnwvcI/xQreEDowCGVzYPa2ih5birV3GayMMaZoxG+Xpc9Qjkq5wm5wwsqzMQMryg2SesqHZ22tdDLT8oKEmNdZRoUKr6PjJPbcy+YCrNXcqP3fWUNd0FfApiDOMM7q+CI7yl49auJigE0wOKG4Z4=
